import fs from "node:fs";
import path from "node:path";
import { TEMPLATES_DIR, renderString, type TemplateVars } from "./template.js";
import type { DetectedService, DockerScan } from "./adopt-scan.js";

/**
 * Draft Docker file generation for `neptr adopt` (the deterministic half of the
 * hybrid Docker workstream). Drafts are best-effort guesses from detected
 * dependencies, carry a DRAFT header, and are verified/finished by the agent in
 * the Docker workstream. Nothing here ever overwrites an existing file.
 */

const DRAFT_HEADER = [
  "# DRAFT — generated by `neptr adopt` from detected dependencies.",
  "# The Docker workstream of the adoption plan verifies and finishes this file.",
].join("\n");

export interface DockerDraftResult {
  /** Root-relative names of files written (e.g. "Dockerfile"). */
  written: string[];
  /** Files not written because they already existed. */
  skipped: string[];
}

/** Per-database default env for the compose service, using ${VAR:-default} interpolation. */
const SERVICE_ENV: Record<string, Array<[name: string, fallback: string]>> = {
  postgres: [
    ["POSTGRES_USER", "app"],
    ["POSTGRES_PASSWORD", "change-me"],
    ["POSTGRES_DB", "{projectName}"],
  ],
  mysql: [
    ["MYSQL_ROOT_PASSWORD", "change-me"],
    ["MYSQL_DATABASE", "{projectName}"],
  ],
};

/** Named volume per db service so data survives container restarts. */
const SERVICE_VOLUMES: Record<string, [volume: string, mount: string]> = {
  postgres: ["pgdata", "/var/lib/postgresql/data"],
  mysql: ["mysqldata", "/var/lib/mysql"],
  mongo: ["mongodata", "/data/db"],
};

/**
 * Build the compose service/depends_on/volumes blocks for detected backing
 * services (dbs + caches). String-built here because template.ts does flat
 * {{var}} replacement with no conditionals; projectName is interpolated in code
 * because renderString never re-scans replacement values.
 */
export function buildComposeBlocks(
  scan: DockerScan,
  projectName: string,
): { services: string; dependsOn: string; volumes: string } {
  const backing = scan.services.filter((s): s is DetectedService & { composeService: string } =>
    Boolean(s.composeService),
  );
  if (backing.length === 0) return { services: "", dependsOn: "", volumes: "" };

  const volumeNames: string[] = [];
  const blocks = backing.map((s) => {
    const lines = [`  ${s.composeService}:`, `    image: ${s.image}`];
    if (s.port) {
      lines.push("    ports:", `      - "${s.port}:${s.port}"`);
    }
    const env = SERVICE_ENV[s.composeService];
    if (env) {
      lines.push("    environment:");
      for (const [name, fallback] of env) {
        const value = fallback.replace("{projectName}", projectName);
        lines.push(`      ${name}: \${${name}:-${value}}`);
      }
    }
    const volume = SERVICE_VOLUMES[s.composeService];
    if (volume) {
      volumeNames.push(volume[0]);
      lines.push("    volumes:", `      - ${volume[0]}:${volume[1]}`);
    }
    return lines.join("\n");
  });

  const dependsOn = ["    depends_on:", ...backing.map((s) => `      - ${s.composeService}`)].join("\n");
  const volumes = volumeNames.length ? ["volumes:", ...volumeNames.map((v) => `  ${v}:`)].join("\n") : "";

  return { services: blocks.join("\n\n"), dependsOn, volumes };
}

/** Render a template with a DRAFT header prepended, never overwriting. */
function writeDraft(
  templateRelPath: string,
  root: string,
  fileName: string,
  vars: TemplateVars,
  header: string,
  result: DockerDraftResult,
): void {
  const dest = path.join(root, fileName);
  if (fs.existsSync(dest)) {
    result.skipped.push(fileName);
    return;
  }
  const src = fs.readFileSync(path.join(TEMPLATES_DIR, templateRelPath), "utf8");
  const rendered = renderString(src, vars);
  // A `# syntax=` parser directive is only honored on the very first line, so
  // the DRAFT header slots in after it instead of burying it.
  const syntaxLine = /^#\s*syntax=[^\n]*\n/.exec(rendered);
  const contents = syntaxLine
    ? `${syntaxLine[0]}${header}\n\n${rendered.slice(syntaxLine[0].length)}`
    : `${header}\n\n${rendered}`;
  fs.writeFileSync(dest, contents);
  result.written.push(fileName);
}

/**
 * Write draft Docker files for the project, choosing the shape from the scan:
 * - existing Docker files at the root → write nothing (inventory covers them);
 * - a server or database detected → generic Node server Dockerfile + compose
 *   with the detected backing services;
 * - a plain Vite app → the same nginx-based setup `neptr new` ships;
 * - neither (library etc.) → write nothing.
 */
export function writeDockerDrafts(
  root: string,
  projectName: string,
  pkg: Record<string, unknown>,
  scan: DockerScan,
): DockerDraftResult {
  const result: DockerDraftResult = { written: [], skipped: [] };
  if (scan.existingFiles.length > 0) return result;

  if (scan.hasServer || scan.hasDb) {
    const scripts = (pkg.scripts as Record<string, string>) ?? {};
    const buildLine = scripts.build ? "RUN npm run build" : "";
    let header = DRAFT_HEADER;
    let startCommand = '["npm", "run", "start"]';
    if (!scripts.start) {
      startCommand = '["node", "dist/index.js"]';
      header += '\n# TODO: no "start" script found — verify the CMD entrypoint.';
    }
    const blocks = buildComposeBlocks(scan, projectName);
    const port = String(scan.appPort);

    writeDraft("adopt-docker/Dockerfile", root, "Dockerfile", { port, buildLine, startCommand }, header, result);
    writeDraft(
      "adopt-docker/docker-compose.yml",
      root,
      "docker-compose.yml",
      {
        projectName,
        port,
        dependsOnBlock: blocks.dependsOn,
        serviceBlocks: blocks.services,
        volumesBlock: blocks.volumes,
      },
      DRAFT_HEADER,
      result,
    );
    writeDraft("docker/.dockerignore", root, ".dockerignore", {}, DRAFT_HEADER, result);
  } else if (scan.hasVite) {
    for (const fileName of ["Dockerfile", "docker-compose.yml", "nginx.conf", ".dockerignore"]) {
      writeDraft(`docker/${fileName}`, root, fileName, { projectName }, DRAFT_HEADER, result);
    }
  }
  return result;
}
