import fs from "node:fs";
import path from "node:path";
import { neptr } from "./theme.js";
import { run } from "./run.js";
import { TEMPLATES_DIR } from "./template.js";

export interface IndexFlags {
  /** Minimal output — used by the SessionStart and pre-commit hooks. */
  quiet?: boolean;
  /** Also install the SessionStart + pre-commit automation into this project. */
  setup?: boolean;
  /** Exit non-zero if the repo map or marker tables are out of date; write nothing (CI guard). */
  check?: boolean;
}

/**
 * Normalize CRLF to LF. Generated content is always LF, but checked-out files
 * may be CRLF (e.g. `core.autocrlf=true` on Windows); comparing and splicing
 * through this keeps `--check` and the rewrite-avoidance stable either way.
 */
function toLf(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

/** Source extensions we scan for exported symbols. */
const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".vue", ".svelte"]);
/** Directories we never descend into. */
const SKIP_DIRS = new Set(["node_modules", "dist", "build", "coverage", ".git"]);

/** Project-root-relative paths of the artifacts we own. Use `/` for links. */
const REPO_MAP_REL = ".docs/REPO_MAP.md";
const KNOWLEDGE_MAP_REL = ".agents/KNOWLEDGE_MAP.md";
const CAPABILITIES_REL = ".agents/CAPABILITIES.md";

const GENERATED_BANNER =
  "<!-- auto-generated by `neptr index`; do not edit by hand. " +
  "The SessionStart and pre-commit hooks keep it fresh. -->";

// --- Repo map generation -----------------------------------------------------

interface FileEntry {
  /** Project-root-relative path, POSIX separators. */
  rel: string;
  /** Sorted, de-duplicated exported symbol names. */
  symbols: string[];
  /** One-line purpose from the top-of-file comment, if any. */
  purpose?: string;
}

/** Recursively collect source files under `src/`, sorted for deterministic output. */
function collectSourceFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        walk(path.join(dir, entry.name));
      } else if (SOURCE_EXTENSIONS.has(path.extname(entry.name))) {
        out.push(path.join(dir, entry.name));
      }
    }
  };
  walk(path.join(root, "src"));
  return out.sort();
}

/** Extract exported symbol names from file contents (regex-based, deterministic). */
function extractExports(content: string): string[] {
  const symbols = new Set<string>();

  // export [async] function|class|const|let|var|interface|type|enum [abstract class] NAME
  const declRe =
    /export\s+(?:async\s+)?(?:abstract\s+)?(?:function\*?|class|const|let|var|interface|type|enum)\s+([A-Za-z_$][\w$]*)/g;
  for (const m of content.matchAll(declRe)) symbols.add(m[1]!);

  // export default function|class NAME  → "NAME (default)"
  const defaultNamed = /export\s+default\s+(?:async\s+)?(?:function\*?|class)\s+([A-Za-z_$][\w$]*)/.exec(content);
  if (defaultNamed) {
    symbols.add(`${defaultNamed[1]} (default)`);
  } else {
    // export default App  (bare identifier at end of statement — the common
    // React `export default App` shape). Reject keyword lead-ins.
    const defaultIdent = /export\s+default\s+([A-Za-z_$][\w$]*)\s*;?\s*$/m.exec(content);
    if (defaultIdent && !["function", "class", "async", "new", "await"].includes(defaultIdent[1]!)) {
      symbols.add(`${defaultIdent[1]} (default)`);
    } else if (/export\s+default\b/.test(content)) {
      symbols.add("default");
    }
  }

  // export { a, b as c, type T } [from "..."]  → a, c (aliases win; skip the `type` keyword)
  for (const m of content.matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const raw of m[1]!.split(",")) {
      const part = raw.trim();
      if (!part) continue;
      const asMatch = /(?:\btype\s+)?[\w$]+\s+as\s+([A-Za-z_$][\w$]*)/.exec(part);
      if (asMatch) {
        symbols.add(asMatch[1]!);
        continue;
      }
      const plain = /^(?:type\s+)?([A-Za-z_$][\w$]*)$/.exec(part);
      if (plain) symbols.add(plain[1]!);
    }
  }

  return [...symbols].sort();
}

/** First line of the top-of-file comment, trimmed to a single readable line. */
function extractPurpose(content: string): string | undefined {
  const lines = content.split("\n");
  let i = 0;
  // Skip a shebang and leading blank lines.
  if (lines[0]?.startsWith("#!")) i++;
  while (i < lines.length && lines[i]!.trim() === "") i++;

  const first = lines[i]?.trim() ?? "";
  let text: string | undefined;
  if (first.startsWith("/**") || first.startsWith("/*")) {
    // Take the first non-empty content line of the block comment.
    for (let j = i; j < lines.length; j++) {
      const cleaned = lines[j]!
        .replace(/^\s*\/\*\*?/, "")
        .replace(/\*\/\s*$/, "")
        .replace(/^\s*\*\s?/, "")
        .trim();
      if (cleaned) {
        text = cleaned;
        break;
      }
      if (lines[j]!.includes("*/")) break;
    }
  } else if (first.startsWith("//")) {
    text = first.replace(/^\/\/+\s?/, "").trim();
  }

  if (!text) return undefined;
  // Single line, capped so the map stays scannable.
  text = text.replace(/\s+/g, " ");
  return text.length > 100 ? text.slice(0, 97) + "..." : text;
}

/** Build the full REPO_MAP.md contents from the project's `src/` tree. */
export function buildRepoMap(root: string): string {
  const files = collectSourceFiles(root);
  const entries: FileEntry[] = files.map((abs) => {
    const rel = path.relative(root, abs).split(path.sep).join("/");
    const content = fs.readFileSync(abs, "utf8");
    return { rel, symbols: extractExports(content), purpose: extractPurpose(content) };
  });

  // Group by immediate parent directory for readability; paths stay full for grep.
  const byDir = new Map<string, FileEntry[]>();
  for (const entry of entries) {
    const dir = entry.rel.includes("/") ? entry.rel.slice(0, entry.rel.lastIndexOf("/")) : ".";
    let bucket = byDir.get(dir);
    if (!bucket) byDir.set(dir, (bucket = []));
    bucket.push(entry);
  }

  const lines: string[] = [
    GENERATED_BANNER,
    "",
    "# Repo Map",
    "",
    "A deterministic index of every file under `src/` — its exported symbols and a",
    "one-line purpose — so an agent can find code in one hop. Regenerated by",
    "`neptr index`. For the conceptual role of each folder see",
    "[module-map.md](module-map.md); for the whole-repo layout see",
    "[../.agents/KNOWLEDGE_MAP.md](../.agents/KNOWLEDGE_MAP.md).",
    "",
  ];

  if (entries.length === 0) {
    lines.push("_No source files found under `src/` yet._", "");
    return lines.join("\n") + "\n";
  }

  for (const dir of [...byDir.keys()].sort()) {
    lines.push(`## ${dir}/`, "");
    for (const entry of byDir.get(dir)!) {
      const syms = entry.symbols.length ? entry.symbols.join(", ") : "_no exports_";
      const purpose = entry.purpose ? ` — ${entry.purpose}` : "";
      lines.push(`- \`${entry.rel}\` — ${syms}${purpose}`);
    }
    lines.push("");
  }

  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

/** Write REPO_MAP.md. Returns true if the file changed on disk. */
function writeRepoMap(root: string, contents: string): boolean {
  const dest = path.join(root, ".docs", "REPO_MAP.md");
  const prev = fs.existsSync(dest) ? fs.readFileSync(dest, "utf8") : "";
  if (toLf(prev) === contents) return false;
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, contents);
  return true;
}

// --- KNOWLEDGE_MAP table refresh ---------------------------------------------

/**
 * Canonical folders and their purposes, in display order. Only those that exist
 * on disk are emitted; any extra tracked top-level dir is appended with a blank
 * purpose for a human to fill in. Keeps the "Folder map" table honest without
 * inventing prose.
 */
const KNOWN_FOLDERS: Array<[string, string]> = [
  ["src", "Application source — see [../.docs/module-map.md](../.docs/module-map.md)"],
  ["public", "Static assets served as-is"],
  ["tests", "Test helpers, fixtures, and cross-cutting integration/e2e suites"],
  [".agents", "Agent rules and this knowledge map (you are here)"],
  [".agents/skills", "Installed skills.sh skills"],
  [".docs", "Project documentation: environment, maps, architecture, documents, features"],
  [".docs/architecture", "Architecture overview and ADRs"],
  [".docs/architecture/adr", "Numbered architectural decision records"],
  [".docs/documents", "Files and documents provided by the user"],
  [".docs/feature", "Feature workspaces: plan/tasks/status/notes per feature"],
  [".github", "GitHub Copilot instructions"],
  [".cursor", "Cursor rules and MCP config"],
  [".claude", "Claude Code settings (SessionStart hook that runs `neptr index`)"],
  [".githooks", "Shared git hooks (pre-commit → `neptr index`)"],
];

/**
 * Canonical key files and their roles. Links are written relative to `.agents/`
 * (where KNOWLEDGE_MAP.md lives). Only files that exist are emitted.
 */
const KNOWN_KEY_FILES: Array<[string, string]> = [
  ["index.html", "HTML entry — Vite serves and builds from here"],
  ["package.json", "Dependencies and npm scripts"],
  ["vite.config.ts", "Vite build/dev configuration"],
  ["vite.config.js", "Vite build/dev configuration"],
  ["tsconfig.json", "TypeScript configuration"],
  [".env.example", "Committed template for `.env`; keep every variable in sync here"],
  [".mcp.json", "MCP servers for Claude Code"],
  [".cursor/mcp.json", "MCP servers for Cursor"],
  [".claude/settings.json", "Claude Code settings — SessionStart hook that refreshes the index"],
  ["Dockerfile", "Container build (dev server + prod)"],
  ["docker-compose.yml", "Dev and prod containers"],
  [".docs/REPO_MAP.md", "Auto-generated index of every `src/` file and its exports (`neptr index`)"],
  [".agents/CAPABILITIES.md", "Installed skills & MCP servers + the policy for choosing among them (`neptr index`)"],
];

function folderMapRows(root: string): string {
  const rows = KNOWN_FOLDERS.filter(([rel]) => fs.existsSync(path.join(root, rel))).map(
    ([rel, purpose]) => `| \`${rel}/\` | ${purpose} |`,
  );
  return rows.join("\n");
}

function keyFileRows(root: string): string {
  const rows = KNOWN_KEY_FILES.filter(([rel]) => fs.existsSync(path.join(root, rel))).map(
    ([rel, role]) => `| [../${rel}](../${rel}) | ${role} |`,
  );
  return rows.join("\n");
}

/** Replace the text between `<!-- neptr:<id>:start -->` and `:end` markers (CRLF-tolerant). */
function spliceMarker(source: string, id: string, replacement: string): { text: string; found: boolean } {
  const re = new RegExp(`(<!-- neptr:${id}:start -->\\r?\\n)[\\s\\S]*?(\\r?\\n<!-- neptr:${id}:end -->)`);
  if (!re.test(source)) return { text: source, found: false };
  return { text: source.replace(re, `$1${replacement}$2`), found: true };
}

/** A marker-table file's current and freshly recomputed contents, both LF-normalized. */
interface MarkerRefresh {
  rel: string;
  dest: string;
  original: string;
  updated: string;
  found: boolean;
}

/** Recompute KNOWLEDGE_MAP.md's marker tables in memory; undefined when the file is absent. */
function computeKnowledgeMap(root: string): MarkerRefresh | undefined {
  const dest = path.join(root, ".agents", "KNOWLEDGE_MAP.md");
  if (!fs.existsSync(dest)) return undefined;
  const original = toLf(fs.readFileSync(dest, "utf8"));
  const folder = spliceMarker(original, "foldermap", folderMapRows(root));
  const keyfiles = spliceMarker(folder.text, "keyfiles", keyFileRows(root));
  return { rel: KNOWLEDGE_MAP_REL, dest, original, updated: keyfiles.text, found: folder.found || keyfiles.found };
}

/**
 * Refresh the Folder map and Key files tables inside KNOWLEDGE_MAP.md between
 * their marker comments, preserving all surrounding prose. Returns true if the
 * file has markers and was (re)written; false (with a warning) if markers are
 * absent — e.g. a pre-existing project retrofitted with `neptr index`.
 */
function refreshKnowledgeMap(root: string, quiet: boolean): boolean {
  const computed = computeKnowledgeMap(root);
  if (!computed) return false;

  if (!computed.found) {
    if (!quiet) {
      neptr.warn(
        "KNOWLEDGE_MAP.md has no neptr markers — skipping table refresh. Add " +
          "<!-- neptr:foldermap:start/end --> and <!-- neptr:keyfiles:start/end --> to enable it.",
      );
    }
    return false;
  }

  if (computed.updated !== computed.original) fs.writeFileSync(computed.dest, computed.updated);
  return true;
}

// --- CAPABILITIES table refresh ----------------------------------------------

/** Flatten to a single markdown-table-safe cell: no newlines, escaped pipes, capped. */
function tableCell(text: string, max = 110): string {
  const clean = text.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
  return clean.length > max ? clean.slice(0, max - 1).trimEnd() + "…" : clean;
}

/** Pull `name`/`description` out of a leading YAML frontmatter block, if present. */
function parseFrontmatter(content: string): { name?: string; description?: string } {
  const m = /^\uFEFF?---\r?\n([\s\S]*?)\r?\n---/.exec(content);
  if (!m) return {};
  const out: { name?: string; description?: string } = {};
  for (const line of m[1]!.split(/\r?\n/)) {
    const kv = /^(name|description)\s*:\s*(.*)$/.exec(line);
    if (!kv) continue;
    let val = kv[2]!.trim().replace(/^["']|["']$/g, "");
    if (val) out[kv[1] as "name" | "description"] = val;
  }
  return out;
}

/** First heading or first non-empty prose line of a doc, for use as a fallback blurb. */
function firstProseLine(content: string): string | undefined {
  const body = content.replace(/^\uFEFF?---\r?\n[\s\S]*?\r?\n---\r?\n/, "");
  for (const raw of body.split(/\r?\n/)) {
    const line = raw.replace(/^#+\s*/, "").trim();
    if (line) return line;
  }
  return undefined;
}

interface SkillRow {
  name: string;
  description: string;
}

/** Scan `.agents/skills/<dir>/` for installed skills and their one-line purpose. */
function collectSkills(root: string): SkillRow[] {
  const dir = path.join(root, ".agents", "skills");
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  const rows: SkillRow[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillDir = path.join(dir, entry.name);
    let name = entry.name;
    let description = "";
    for (const file of ["SKILL.md", "README.md"]) {
      const p = path.join(skillDir, file);
      if (!fs.existsSync(p)) continue;
      const content = fs.readFileSync(p, "utf8");
      const fm = parseFrontmatter(content);
      if (fm.name) name = fm.name;
      description = fm.description ?? firstProseLine(content) ?? "";
      if (description) break;
    }
    rows.push({ name, description });
  }
  // Code-unit sort (not localeCompare): output must be byte-identical across machines.
  return rows.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

interface McpRow {
  key: string;
  launch: string;
  needsEnv: boolean;
}

/** Read the `mcpServers` map from `.mcp.json`, tolerating a missing/malformed file. */
function collectMcpServers(root: string): McpRow[] {
  const file = path.join(root, ".mcp.json");
  if (!fs.existsSync(file)) return [];
  let parsed: { mcpServers?: Record<string, unknown> };
  try {
    parsed = JSON.parse(fs.readFileSync(file, "utf8")) as { mcpServers?: Record<string, unknown> };
  } catch {
    return [];
  }
  const servers = parsed.mcpServers;
  if (!servers || typeof servers !== "object") return [];
  const rows: McpRow[] = [];
  for (const [key, raw] of Object.entries(servers)) {
    const cfg = (raw ?? {}) as { command?: string; args?: unknown; url?: string; env?: Record<string, unknown> };
    let launch: string;
    if (typeof cfg.command === "string") {
      const args = Array.isArray(cfg.args) ? cfg.args.map(String) : [];
      launch = [cfg.command, ...args].join(" ");
    } else if (typeof cfg.url === "string") {
      launch = cfg.url;
    } else {
      launch = "custom";
    }
    rows.push({ key, launch, needsEnv: !!cfg.env && Object.keys(cfg.env).length > 0 });
  }
  // Code-unit sort (not localeCompare): output must be byte-identical across machines.
  return rows.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

/** Render the skills inventory as a markdown table (or an empty-state line). */
function skillsTable(root: string): string {
  const rows = collectSkills(root);
  if (rows.length === 0) return '_No skills installed yet. Add one with `neptr skill "<keywords>"`._';
  const lines = ["| Skill | What it's for |", "| --- | --- |"];
  for (const r of rows) lines.push(`| \`${tableCell(r.name, 60)}\` | ${r.description ? tableCell(r.description) : "—"} |`);
  return lines.join("\n");
}

/** Render the MCP inventory as a markdown table (or an empty-state line). */
function mcpTable(root: string): string {
  const rows = collectMcpServers(root);
  if (rows.length === 0) return '_No MCP servers configured yet. Add one with `neptr mcp "<keywords>"`._';
  const lines = ["| Server | Launch | Needs secret |", "| --- | --- | --- |"];
  for (const r of rows) {
    lines.push(`| \`${tableCell(r.key, 60)}\` | \`${tableCell(r.launch, 80)}\` | ${r.needsEnv ? "yes" : "no"} |`);
  }
  return lines.join("\n");
}

/**
 * Refresh the Skills and MCP servers inventory tables inside CAPABILITIES.md
 * between their marker comments, preserving the hand-written usage policy around
 * them. Returns true if the file has markers and was (re)written; false when the
 * file or markers are absent (e.g. a project scaffolded before this feature).
 */
function refreshCapabilities(root: string, quiet: boolean): boolean {
  const computed = computeCapabilities(root);
  if (!computed) return false;

  if (!computed.found) {
    if (!quiet) {
      neptr.warn(
        "CAPABILITIES.md has no neptr markers — skipping inventory refresh. Add " +
          "<!-- neptr:skills:start/end --> and <!-- neptr:mcp:start/end --> to enable it.",
      );
    }
    return false;
  }

  if (computed.updated !== computed.original) fs.writeFileSync(computed.dest, computed.updated);
  return true;
}

/** Recompute CAPABILITIES.md's inventory tables in memory; undefined when the file is absent. */
function computeCapabilities(root: string): MarkerRefresh | undefined {
  const dest = path.join(root, ".agents", "CAPABILITIES.md");
  if (!fs.existsSync(dest)) return undefined;
  const original = toLf(fs.readFileSync(dest, "utf8"));
  const skills = spliceMarker(original, "skills", skillsTable(root));
  const mcp = spliceMarker(skills.text, "mcp", mcpTable(root));
  return { rel: CAPABILITIES_REL, dest, original, updated: mcp.text, found: skills.found || mcp.found };
}

// --- Automation install (hooks) ----------------------------------------------

const SESSION_START_COMMAND = "neptr index --quiet";

/** Idempotently add a SessionStart hook running `neptr index --quiet` to .claude/settings.json. */
function installClaudeHook(root: string): void {
  const dest = path.join(root, ".claude", "settings.json");
  let settings: Record<string, unknown> = {};
  if (fs.existsSync(dest)) {
    try {
      settings = JSON.parse(fs.readFileSync(dest, "utf8")) as Record<string, unknown>;
    } catch {
      throw new Error(".claude/settings.json exists but could not be parsed — fix or remove it, then retry.");
    }
  }

  const hooks = (settings.hooks ??= {}) as Record<string, unknown>;
  const sessionStart = (hooks.SessionStart ??= []) as Array<{ hooks?: Array<{ command?: string }> }>;

  const alreadyThere = sessionStart.some((group) =>
    (group.hooks ?? []).some((h) => typeof h.command === "string" && h.command.includes("neptr index")),
  );
  if (alreadyThere) return;

  sessionStart.push({ hooks: [{ type: "command", command: SESSION_START_COMMAND }] } as never);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, JSON.stringify(settings, null, 2) + "\n");
}

/**
 * Ensure .gitattributes pins the generated docs to LF, so autocrlf checkouts
 * don't turn every `neptr index` run into churn (or fail `--check` in CI).
 * Appends only the missing NEPTR block; never rewrites existing user content.
 */
function installGitAttributes(root: string): void {
  const src = fs.readFileSync(path.join(TEMPLATES_DIR, "project", ".gitattributes"), "utf8");
  const dest = path.join(root, ".gitattributes");
  const existing = fs.existsSync(dest) ? fs.readFileSync(dest, "utf8") : "";
  if (existing.includes("# NEPTR generated docs")) return;
  fs.writeFileSync(dest, (existing.trimEnd() ? existing.trimEnd() + "\n\n" : "") + src);
}

/** Copy the tracked pre-commit hook into .githooks/ and mark it executable. */
function installGitPreCommitHook(root: string): void {
  const src = path.join(TEMPLATES_DIR, ".githooks", "pre-commit");
  const destDir = path.join(root, ".githooks");
  const dest = path.join(destDir, "pre-commit");
  fs.mkdirSync(destDir, { recursive: true });
  fs.copyFileSync(src, dest);
  try {
    fs.chmodSync(dest, 0o755);
  } catch {
    // chmod is a no-op / may throw on some Windows setups; the hook still runs
    // via Git's bundled bash under core.hooksPath.
  }
}

/** Point git at .githooks/ so the pre-commit hook activates (retrofit path). */
async function activateGitHooks(root: string): Promise<void> {
  if (!fs.existsSync(path.join(root, ".git"))) return;
  await run("git", ["config", "core.hooksPath", ".githooks"], {
    cwd: root,
    stdio: "pipe",
    timeout: 15_000,
  });
}

/** Install both hooks + the initial REPO_MAP into an already-scaffolded project. */
export function installIndexing(root: string): void {
  // Install the hooks first so `.claude/` and `.githooks/` exist before we
  // refresh the Folder map — otherwise they'd be missing from the first build.
  installClaudeHook(root);
  installGitPreCommitHook(root);
  installGitAttributes(root);
  writeRepoMap(root, buildRepoMap(root));
  refreshKnowledgeMap(root, true);
  refreshCapabilities(root, true);
}

// --- Command entry point -----------------------------------------------------

/** `neptr index` — (re)build the repo map that Claude Code reads. */
export async function runIndex(flags: IndexFlags): Promise<void> {
  const root = process.cwd();
  if (!fs.existsSync(path.join(root, "src"))) {
    if (!flags.quiet) neptr.warn("No `src/` directory here — nothing to index.");
    return;
  }

  const map = buildRepoMap(root);

  if (flags.check) {
    const stale: string[] = [];
    const dest = path.join(root, ".docs", "REPO_MAP.md");
    const current = fs.existsSync(dest) ? fs.readFileSync(dest, "utf8") : "";
    if (toLf(current) !== map) stale.push(REPO_MAP_REL);
    for (const computed of [computeKnowledgeMap(root), computeCapabilities(root)]) {
      if (computed?.found && computed.updated !== computed.original) stale.push(computed.rel);
    }
    if (stale.length > 0) {
      if (!flags.quiet) {
        neptr.warn(`${stale.join(", ")} ${stale.length === 1 ? "is" : "are"} out of date — run \`neptr index\`.`);
      }
      process.exitCode = 1;
    } else if (!flags.quiet) {
      neptr.say("Index is up to date.");
    }
    return;
  }

  const mapChanged = writeRepoMap(root, map);
  const refreshed = refreshKnowledgeMap(root, flags.quiet ?? false);
  const capsRefreshed = refreshCapabilities(root, flags.quiet ?? false);

  if (flags.setup) {
    installClaudeHook(root);
    installGitPreCommitHook(root);
    installGitAttributes(root);
    await activateGitHooks(root);
  }

  if (!flags.quiet) {
    const bits = [`${REPO_MAP_REL}${mapChanged ? " (updated)" : " (unchanged)"}`];
    if (refreshed) bits.push(`refreshed ${KNOWLEDGE_MAP_REL} tables`);
    if (capsRefreshed) bits.push(`refreshed ${CAPABILITIES_REL} inventory`);
    if (flags.setup) bits.push("installed SessionStart + pre-commit hooks");
    neptr.success(`Indexed \`src/\` → ${bits.join(", ")}.`);
  }
}
